# Seta Direita/Esquerda: Avança/Retrocede 10 segundos
RIGHT seek  10
LEFT  seek -10

# CTRL + Seta Direita/Esquerda: Avança/Retrocede 1 minuto
CTRL+RIGHT seek  60
CTRL+LEFT  seek -60

# Shift + Seta Direita/Esquerda: Avança/Retrocede 2 segundos
SHIFT+RIGHT seek  2
SHIFT+LEFT  seek -2