# Salva a posição do vídeo ao sair
save-position-on-quit=yes

# Garante que a janela do player não ultrapasse o tamanho da tela
autofit-larger=100%x100%

# Inicia em tela cheia
fullscreen=yes

# Substitui os controles por uma barra fina e a mantém visível
#script-opts=osc-layout=bottombar,osc-visibility=always

